use thiserror::Error;

/// Errors generated by the numeric type impls
#[derive(Clone, Debug, Error, PartialEq)]
#[non_exhaustive]
pub enum Error {
    /// an unsigned-varint error
    #[error(transparent)]
    UnsignedVarintDecode(#[from] unsigned_varint::decode::Error),
}
